apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-eso-example
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend-k8s-auth
    kind: ClusterSecretStore
  target:
    name: output-secret
  data:
  - secretKey: foobar
    remoteRef:
      key: eso/foo
      property: my-value
