apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    service: secret-manager
    version: 1.0.0
    env: dev
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: eso
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: v2
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: vault-token
          namespace: external-secrets
          key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: aHZzLnR0WXF1MURsT1g3YmhTUmlwY1J0WnJ3SQ== # "root - so I dont recommend this setting"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: example-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: eso/foo
      property: my-value

---
# will create a secret with:
# kind: Secret
# metadata:
#   name: example-sync
# data:
#   foobar: czNjcjN0
